const actionTypes = {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    LOGIN_EPR: 'LOGIN_EPR',
    LOGOUT_EPR: 'LOGOUT_EPR',
    LOGIN_ADM: 'LOGIN_ADM',
    LOGOUT_ADM: 'LOGOUT_ADM',
    SET_CART: 'SET_CART',
    REMOVE_PRODUCT_CART: 'REMOVE_PRODUCT_CART',
    NUS_PRODUCT_CART: 'NUS_PRODUCT_CART',
    MINUS_PRODUCT_CART: 'MINUS_PRODUCT_CART'
}

export default actionTypes